### ISSUE TITLE
Enchantments such as the Steel Enchantment do not adopt the effects of shield items from Thorium

### ISSUE THREAD

**Issue by InQuognito** [Fargowilta/FargowiltasSouls#203]
For instance, the Steel Enchantment uses the Thorium Shield to craft, so theoretically, on top of the other effects, the enchantment should increase defense by 3 and generate a 16 life shield. I don't know if this is intended or not but I miss my shields :(

**Comment by Fargowilta** [comment]
it is intended yea sorry ! lol
