### ISSUE TITLE
Soul of Eternity/WingSlot Crash

### ISSUE THREAD

**Issue by Lillber2020** [Fargowilta/FargowiltasSouls#344]
Equipping the Soul of Eternity to the Wing Slot in the Wing Slot mod then unequipping it causes the game to crash when you highlight the Soul of Eternity. This happens even when moving it from the wing slot to an actual accessory slot and also strangely happens when you unequip without highlighting it (such as throwing it then picking it up) then saving and exiting the world then reopening it. The error that happens is as follows:
https://pastebin.com/qCv7NWwh

**Comment by Steviegt6** [comment]
This appears to be an issue with WingSlot's code, not Fargo's Souls.

[(This was already reported on their repository as well).](https://github.com/abluescarab/tModLoader-WingSlot/issues/33)
